### ISSUE TITLE
Add the Application name to the dashboard page

### ISSUE THREAD

**Issue by dgomezg** [AxonFramework/AxonFramework-FireStarter#58]
### Enhancement Description

It would be nice to have the application name in the title of the Firestarter page. For scenarios in which you have several different services running, and you have the Axon FireStarter configured for all those modules, there will be different pages for the different applications, and it will be useful to know which application you are adding the taints to.

### Current Behaviour

Right now the Axon Fire Starter main page looks like this:
![image](https://github.com/AxonFramework/AxonFramework-FireStarter/assets/1894346/d5e44442-f067-4738-af24-da217db6dc6d)

If you have the Axon Firestarter added to several different modules, the only way to know which application you are interacting with is by looking at the port:
<img width="1631" alt="image" src="https://github.com/AxonFramework/AxonFramework-FireStarter/assets/1894346/c317dfda-5cc2-4a5a-ad85-b71a4f6e58c6">

### Wanted Behaviour

It would be useful to add the value of `spring.application.name` property to both the title and the header of the `Axon Firestarter` main page:
<img width="1645" alt="image" src="https://github.com/AxonFramework/AxonFramework-FireStarter/assets/1894346/f3225ba0-c280-46d5-93ee-4a5608ccf0dd">

**Comment by smcvb** [comment]
This issue has been resolved by PR #63.
